- name: Combine all systemd service configuration options
  set_fact:
    _systemd_service_config: "{{ docker_systemd_service_config_tweaks + docker_systemd_service_config }}"

- name: Ensure /etc/systemd/system/docker.service.d directory exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  become: yes

- name: Setup default Docker drop-in to enable use of environment file
  template:
    src: drop-ins/default.conf.j2
    dest: /etc/systemd/system/docker.service.d/default.conf
  become: yes
  register: _systemd_docker_dropin
  vars:
    systemd_envs_dir: "{{ docker_systemd_envs_dir[_docker_os_dist] }}"
    systemd_service_conf: "{{ _systemd_service_config }}"

- name: Setup Docker environment file {{ docker_systemd_envs_dir[_docker_os_dist] }}/docker-envs
  template:
    src: docker-envs.j2
    dest: "{{ docker_systemd_envs_dir[_docker_os_dist] }}/docker-envs"
  become: yes
  notify: restart docker
  vars:
    docker_opts: "{{ docker_daemon_opts }}"

- name: Force daemon reload of systemd
  systemd: 
    daemon_reload: yes
  become: yes
  notify: restart docker
  when: _systemd_docker_dropin|changed