---
- name: Set docker-ce package state to latest
  set_fact:
    _docker_pkg_state: 'latest'
  when: docker_latest_version | bool

- name: Ensure docker-ce is installed
  become: true
  package:
    name: "{{ docker_pkg_name }}"
    state: "{{ _docker_pkg_state | default('present') }}"
  register: _pkg_result
  until: _pkg_result|succeeded
  notify: restart docker
