---
- name: Set distribution facts
  set_fact:
    _docker_os_dist: "{{ ansible_distribution }}"
    _docker_os_dist_release: "{{ ansible_distribution_release }}"
    _docker_os_dist_major_version: "{{ ansible_distribution_major_version }}"
    _docker_os_dist_check: yes
  tags: ["install", "configure"]

- name: Reinterpret distribution facts for Linux Mint 18
  set_fact:
    _docker_os_dist: "Ubuntu"
    _docker_os_dist_release: "xenial"
    _docker_os_dist_major_version: "16"
  when:
    _docker_os_dist == "Linux Mint" and
    _docker_os_dist_major_version == "18"
  tags: ["install", "configure"]

- name: Reset role variables
  set_fact:
    docker_systemd_service_config_tweaks: []
    docker_service_envs: {}

- name: Temporary handling of deprecated variable docker_enable_ce_edge (#54)
  set_fact:
    docker_channel: edge
  when:
    - docker_enable_ce_edge is defined
    - docker_enable_ce_edge

- name: Compatibility and distribution checks
  include_tasks: checks.yml
  when: docker_do_checks | bool
  tags: ["install", "configure"]

- name: Setup Docker package repositories
  include_tasks: setup-repository.yml
  tags: ["install"]

- name: Remove Docker versions before Docker CE
  include_tasks: remove-pre-docker-ce.yml
  when: docker_remove_pre_ce | bool
  tags: ["install"]

- name: Install Docker
  include_tasks: install-docker.yml
  tags: ["install"]

- name: Configure audit logging
  include_tasks: setup-audit.yml
  tags: ["configure"]

- name: Apply workarounds for bugs and/or tweaks
  include_tasks: bug-tweaks.yml
  tags: ["configure"]

- name: Configure Docker
  include_tasks: configure-docker.yml
  tags: ["configure"]

- name: Postinstall tasks
  include_tasks: postinstall.yml
  tags: ["install"]