---
- name: Determine Docker version
  command: bash -c "docker version | grep Version | awk '{print $2}'"
  ignore_errors: yes
  changed_when: false
  register: _cmd_docker_version

- name: Set fact if old Docker installation shall be removed
  set_fact:
    _remove_old_docker: "{{ docker_remove_pre_ce | bool }} and not \
      {{ _cmd_docker_version.stdout_lines[0] | search('-ce') }}"
  when: _cmd_docker_version.stdout_lines is defined and _cmd_docker_version.stdout_lines[0] is defined

- name: Check if Docker is running
  become: true
  systemd:
    name: docker
  ignore_errors: yes
  register: _service_docker_status
  when: _remove_old_docker | default(False) | bool

- name: Stop Docker service
  service:
    name: docker
    state: stopped
  when: "_service_docker_status.rc | default(1) == 0"

- name: Remove old Docker installation before Docker CE
  become: true
  package:
    name: "{{ item }}"
    state: absent
  when: _remove_old_docker | default(False) | bool
  with_items:
    - "{{ docker_old_packages[_docker_os_dist] }}"
