---
- name: Ensure python and deps for Ansible modules
  become: true
  raw: dnf install -y python2 python2-dnf libselinux-python
  changed_when: false
  when: _docker_os_dist == "Fedora"

- name: Update APT cache
  become: true
  apt:
    update_cache: yes
  changed_when: false
  register: _pkg_result
  until: _pkg_result|succeeded
  when: _docker_os_dist == "Ubuntu" or
        _docker_os_dist == "Debian"

- name: Ensure packages are installed for repository setup
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_repository_related_packages[_docker_os_dist] }}"
  register: _pkg_result
  until: _pkg_result|succeeded
  when: _docker_os_dist == "Ubuntu" or
        _docker_os_dist == "Debian" or
        _docker_os_dist == "CentOS" or
        _docker_os_dist == "RedHat"

- name: Add Docker official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/{{ _docker_os_dist|lower }}/gpg
    state: present
  register: _pkg_result
  until: _pkg_result|succeeded
  when: (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version > '14') or
        (_docker_os_dist == "Debian" and _docker_os_dist_major_version > '7')

- name: Add Docker APT key (alternative for older Ubuntu systems without SNI).
  become: true
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  args:
    warn: false
  changed_when: false
  when: (_docker_os_dist == "Ubuntu" and _docker_os_dist_major_version == '14') or (_docker_os_dist == "Debian" and
    _docker_os_dist_major_version == '7')
  tags:
    - skip_ansible_lint

- name: Determine channels to be enabled and/or disabled
  set_fact:
    _docker_disable_channels: "{{ docker_channels | difference(_docker_merged_channels) }}"
    _docker_enable_channels: "{{ docker_channels | intersect(_docker_merged_channels) }}"
  vars:
    _docker_mandatory_channel: []
    _docker_merged_channels: "{{ _docker_mandatory_channel }} + [ '{{ docker_channel }}' ]"

- name: Add Docker CE repository with correct channels (Ubuntu/Debian)
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ _docker_os_dist|lower }} \
      {{ _docker_os_dist_release }} {{ _docker_enable_channels | join(' ') }}"
    state: present
    filename: 'docker-ce'
  when: _docker_os_dist == "Ubuntu" or
        _docker_os_dist == "Debian"

# Backport is required but not documented by Docker: https://github.com/moby/moby/issues/16878
- name: Add backport repository for Debian Wheezy
  become: true
  apt_repository:
    repo: deb [arch=amd64] http://ftp.debian.org/debian wheezy-backports main
    state: present
    filename: 'debian-backport'
  when: _docker_os_dist == "Debian" and _docker_os_dist_major_version == '7'

- name: Add Docker CE repository (Fedora/CentOS/RedHat)
  become: true
  get_url:
    url: "{{ docker_repository_url[_docker_os_dist] }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  register: _docker_repo
  when: _docker_os_dist == "CentOS" or
        _docker_os_dist == "Fedora" or
        _docker_os_dist == "RedHat"

- name: Disable Docker CE repository channels (Fedora/CentOS/RedHat)
  become: true
  shell: "{{ docker_cmd_enable_disable_edge_repo[_docker_os_dist] }}"
  with_items: "{{ _docker_disable_channels }}"
  changed_when: false
  vars:
    _item_enabled: false
  when: _docker_os_dist == "CentOS" or
        _docker_os_dist == "Fedora" or
        _docker_os_dist == "RedHat"
  tags:
    - skip_ansible_lint

- name: Enable Docker CE repository channels (Fedora/CentOS/RedHat)
  become: true
  shell: "{{ docker_cmd_enable_disable_edge_repo[_docker_os_dist] }}"
  with_items: "{{ _docker_enable_channels }}"
  changed_when: false
  vars:
    _item_enabled: true
  when: _docker_os_dist == "CentOS" or
        _docker_os_dist == "Fedora" or
        _docker_os_dist == "RedHat"
  tags:
    - skip_ansible_lint

# disable rt-beta so we don't get a 403 error retrieving repomd.xml
- name: Check if rhel-7-server-rt-beta-rpms Repository is enabled (RedHat)
  become: true
  shell: "subscription-manager repos --list-enabled | grep rhel-7-server-rt-beta-rpms"
  register: cmd_rhel_rt_beta_repo_enabled
  when: _docker_os_dist == "RedHat"
  changed_when: false
  failed_when: cmd_rhel_rt_beta_repo_enabled.rc not in [ 0, 1 ]
  tags:
    - skip_ansible_lint

- name: Disable rhel-7-server-rt-beta-rpms Repository (RedHat)
  become: true
  shell: "subscription-manager repos --disable=rhel-7-server-rt-beta-rpms"
  when: _docker_os_dist == "RedHat" and cmd_rhel_rt_beta_repo_enabled.rc == 0
  tags:
    - skip_ansible_lint

# container-selinux package wants this
- name: Check if rhel-7-server-extras-rpms Repository is enabled (RedHat)
  become: true
  shell: "subscription-manager repos --list-enabled | grep rhel-7-server-extras-rpms"
  register: cmd_rhel_extras_repo_enabled
  when: _docker_os_dist == "RedHat"
  changed_when: false
  failed_when: cmd_rhel_extras_repo_enabled.rc not in [ 0, 1 ]
  tags:
    - skip_ansible_lint

- name: Enable rhel-7-server-extras-rpms Repository (RedHat)
  become: true
  shell: "subscription-manager repos --enable=rhel-7-server-extras-rpms"
  when: _docker_os_dist == "RedHat" and cmd_rhel_extras_repo_enabled.rc == 1
  tags:
    - skip_ansible_lint

- name: Update repository cache
  become: true
  shell: "{{ docker_cmd_update_repo_cache[_docker_os_dist] }}"
  args:
    warn: false
  changed_when: false
  tags:
    - skip_ansible_lint