---
- name: Include tasks for distribution variety {{ ansible_distribution_file_variety }} to setup repository
  include_tasks: setup-repository-{{ ansible_distribution_file_variety }}.yml

- name: Update repository cache
  become: true
  shell: "{{ docker_cmd_update_repo_cache[_docker_os_dist] | default(docker_cmd_update_repo_cache[ansible_distribution_file_variety]) }}"
  args:
    warn: false
  changed_when: false
  register: _result
  until: _result is succeeded
  when: docker_network_access | bool
  tags:
    - skip_ansible_lint